In [1]:
import torch
import torchvision
import torchvision.transforms as transforms

In [2]:
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=4,
                                          shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=4,
                                         shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified


In [1]:
import mxnet as mx
import numpy as np
import pickle
import cv2

def extractImagesAndLabels(file):
    f = open(file, 'rb')
    dict = pickle.load(f, encoding='latin1')
    images = dict['data']
    images = np.reshape(images, (10000, 3, 32, 32))
    labels = dict['labels']
    imagearray = mx.nd.array(images)
    labelarray = mx.nd.array(labels)
    return imagearray, labelarray

def extractCategories(file):
    f = open(file, 'rb')
    dict = pickle.load(f, encoding='latin1')
    return dict['label_names']

def saveCifarImage(array, path, file):
    # array is 3x32x32. cv2 needs 32x32x3
    array = array.asnumpy().transpose(1,2,0)
    # array is RGB. cv2 needs BGR
    array = cv2.cvtColor(array, cv2.COLOR_RGB2BGR)
    # save to PNG file
    return cv2.imwrite(path+file+".png", array)

In [2]:
classes = {}
imgarray, lblarray = extractImagesAndLabels("data/cifar-10-batches-py/data_batch_1")
print(imgarray)
print(lblarray)


[[[[ 59.  43.  50. ... 158. 152. 148.]
   [ 16.   0.  18. ... 123. 119. 122.]
   [ 25.  16.  49. ... 118. 120. 109.]
   ...
   [208. 201. 198. ... 160.  56.  53.]
   [180. 173. 186. ... 184.  97.  83.]
   [177. 168. 179. ... 216. 151. 123.]]

  [[ 62.  46.  48. ... 132. 125. 124.]
   [ 20.   0.   8. ...  88.  83.  87.]
   [ 24.   7.  27. ...  84.  84.  73.]
   ...
   [170. 153. 161. ... 133.  31.  34.]
   [139. 123. 144. ... 148.  62.  53.]
   [144. 129. 142. ... 184. 118.  92.]]

  [[ 63.  45.  43. ... 108. 102. 103.]
   [ 20.   0.   0. ...  55.  50.  57.]
   [ 21.   0.   8. ...  50.  50.  42.]
   ...
   [ 96.  34.  26. ...  70.   7.  20.]
   [ 96.  42.  30. ...  94.  34.  34.]
   [116.  94.  87. ... 140.  84.  72.]]]


 [[[154. 126. 105. ...  91.  87.  79.]
   [140. 145. 125. ...  96.  77.  71.]
   [140. 139. 115. ...  79.  68.  67.]
   ...
   [175. 156. 154. ...  42.  61.  93.]
   [165. 156. 159. ... 103. 123. 131.]
   [163. 158. 163. ... 143. 143. 143.]]

  [[177. 137. 104. ...  9

In [4]:
categories = extractCategories("./data/cifar-10-batches-py/batches.meta")